---
- hosts: localhost
  gather_facts: true

  tasks:
     
    - name: Gather Oneview version facts
      hpe.oneview.oneview_version_facts:
        hostname: "{{ oneview_hostname }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
      delegate_to: localhost

    - debug: var=version

    - name: Gather user facts
      hpe.oneview.oneview_user_facts:
        hostname: "{{ oneview_hostname }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
      delegate_to: localhost

    - debug: var=users
