---
- hosts: localhost
  gather_facts: no
  become: false

  tasks:
  - name: Make sure requirements are met to run vmware modules
     become: true
     ansible.builtin.pip:
      name: pyVmomi
      state: present 
    
  - name: Gather all domain user and group of vsphere.local
    community.vmware.vcenter_domain_user_group_info:
      hostname: "{{ vcenter_name }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: false
      domain: hpecic.net
      search_string: ''
    #register: gather_all_domain_user_group_result
    delegate_to: localhost

