---
- hosts: localhost
  gather_facts: no
  become: true

  tasks:

  - name: Gather all domain user and group of vsphere.local
    community.vmware.vcenter_domain_user_group_info:
      hostname: "{{ vcenter_name }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: false
      domain: hpecic.net
      search_string: ''
    register: gather_all_domain_user_group_result
    delegate_to: localhost

